[build]
  publish = "dist"
  command = "pnpm build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  VITE_DEV_MODE = "false"

[context.deploy-preview.environment]
  VITE_DEV_MODE = "false"